/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.managercafe.view;

import com.managercafe.model.billModel;
import com.managercafe.model.revenueModel;
import com.managercafe.service.IBillService;
import com.managercafe.service.IRevenueService;
import com.managercafe.service.imp.BillService;
import com.managercafe.service.imp.RevenueService;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huy
 */
public class frmRevenue extends javax.swing.JFrame {

    /**
     * Creates new form frmRevenue
     */
    public frmRevenue() {
        initComponents();
    }

    List<billModel> listBill = new ArrayList<>();
    private final IBillService billService = new BillService();
    private final IRevenueService revenueService = new RevenueService();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRevenue = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetailBill_In_Revenue = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRevenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRevenueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRevenue);

        tblDetailBill_In_Revenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetailBill_In_Revenue);

        jLabel1.setText("List Order ");

        jLabel2.setText("Detail Order");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTableRevenue(List<billModel> list) {
        String[] header = {"Id Bill", "User Id", "Total", "Created By", "Created Date"};
        DefaultTableModel headerModel = new DefaultTableModel(header, 0);
        tblRevenue.setModel(headerModel);
        Vector row = null;
        DefaultTableModel model = (DefaultTableModel) tblRevenue.getModel();

        for (billModel bill : list) {
            row = new Vector();
            row.add(bill.getId());
            row.add(bill.getUserId());
            row.add(bill.getTotal());

            row.add(bill.getCreatedby());
            row.add(bill.getCreateddate());
            model.addRow(row);
            tblRevenue.setModel(model);

        }
        tblRevenue.setModel(model);
    }
    private void setTableBillInRevenue(List<revenueModel> list) {
        String[] header = {"Id Bill", "User Id","Full Name", "Total","Product ID", 
            "Name Product","Quantity","Total Product","Price","Size","Type","Created Date"};
        DefaultTableModel headerModel = new DefaultTableModel(header, 0);
        tblDetailBill_In_Revenue.setModel(headerModel);
        Vector row = null;
        DefaultTableModel model = (DefaultTableModel) tblDetailBill_In_Revenue.getModel();

        for (revenueModel bill : list) {
            row = new Vector();
            row.add(bill.getId());
            row.add(bill.getUserId());
            row.add(bill.getFullname());
            row.add(bill.getTotal());
            row.add(bill.getProductId());
            row.add(bill.getNameProduct());
            row.add(bill.getQuantity());
            row.add(bill.getTotalProduct());
            row.add(bill.getPrice());
            row.add(bill.getSize());
            row.add(bill.getType());
            row.add(bill.getCreateddate());
            model.addRow(row);
            tblDetailBill_In_Revenue.setModel(model);

        }
        tblDetailBill_In_Revenue.setModel(model);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listBill = billService.findAll();
        setTableRevenue(listBill);
    }//GEN-LAST:event_formWindowOpened

    private void tblRevenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRevenueMouseClicked
        List<revenueModel> listRevenue = revenueService.findAll(Long.parseLong(tblRevenue.getModel().getValueAt(tblRevenue.getSelectedRow(), 0).toString()));
        setTableBillInRevenue(listRevenue);
    }//GEN-LAST:event_tblRevenueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRevenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRevenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRevenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRevenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRevenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDetailBill_In_Revenue;
    private javax.swing.JTable tblRevenue;
    // End of variables declaration//GEN-END:variables
}
